site_name: GreatAI documentation
site_description: GreatAI helps you easily transform your prototype AI code into production-ready software.
site_author: András Schmelczer

repo_url: https://github.com/schmelczer/great-ai
repo_name: schmelczer/great-ai
edit_uri: edit/main/docs/

theme:
  name: "material"
  custom_dir: docs/overrides
  homepage: https://great-ai.scoutinscience.com
  favicon: media/favicon.ico
  features:
    - content.code.annotate
    - content.tooltips
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

watch:
- docs
- mkdocs.yaml

plugins:
  - git-revision-date-localized:
  - mkdocstrings
  - search
  - mkdocs-jupyter:
      include_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - abbr
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Overview: index.md
  - Tutorial: 
    - tutorial/index.md
    - tutorial/train.ipynb
    - tutorial/deploy.ipynb
  - User Guides:
    - Simple AI lifecycle with classification:
      - "Step 1: data": simple/data.ipynb
      - "Step 2: train": simple/train.ipynb
      - "Step 3: deploy": simple/deploy.ipynb
  - reference.md
  - explanation.md

